# Generated by Django 5.0.7 on 2024-07-30 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('mandatory', models.BooleanField(default=True)),
                ('configurtion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.configuration')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.machinetype')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.platform')),
            ],
        ),
    ]
