# Generated by Django 5.0.7 on 2024-07-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='configurtion',
            new_name='configuration',
        ),
    ]
