# Generated by Django 5.0.7 on 2024-07-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0002_rename_configurtion_scenario_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='test',
        ),
    ]
